server.port=8080
server.servlet.context-path=/store

#database primary
spring.datasource.url=jdbc:mysql://localhost:3307/storedb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=10

#secondary
spring.datasource.secondary.url=jdbc:mysql://localhost:3308/storedb
spring.datasource.secondary.username=root
spring.datasource.secondary.password=root
spring.datasource.secondary.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#OAuth2
#Setup
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:5173/login-success

#Google
spring.security.oauth2.client.registration.google.client-id=384241258749-3lk4emo83tf3ndreqrlstj7e1dpv03b1.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

jwt.signerKey=oa+ji4n1sseImLWqvR21hqOBCyagWLxv+K2TPia8xypUKUQJw/aE2QHsAvRQEXUF
jwt.valid-duration=7200
jwt.refreshable-duration=72000

payment.vnPay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
payment.vnPay.tmnCode=PTX1D0VC
payment.vnPay.secretKey=2K5CXZRX2AHBJJRDMO371IMED76U52XI
payment.vnPay.returnUrl=http://localhost:5173/order/list
payment.vnPay.version=2.1.0
payment.vnPay.command=pay
payment.vnPay.orderType=other

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# --- C?u hình Redis ---
spring.data.redis.port=6379
spring.data.redis.host=localhost
spring.data.redis.repositories.enabled=true

# --- C?u hình Email ---
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=nguyendanggiang99@gmail.com
spring.mail.password=bmdl exir oumv ipsk
spring.mail.protocol=smtps
spring.mail.properties.mail.transport.protocol=smtps
spring.mail.properties.mail.smtps.auth=true
spring.mail.properties.mail.smtps.starttls.enable=true
spring.mail.properties.mail.smtps.timeout=8000
